const shuffle = () => {
  var songs = [
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/979782958&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/kaiser_wkg-srdbeatz" title="bailout + @kaiser_wkg" target="_blank" style="color: #cccccc; text-decoration: none;">bailout + @kaiser_wkg</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/934854793&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/derail" title="derail + @1opgloryboyz" target="_blank" style="color: #cccccc; text-decoration: none;">derail + @1opgloryboyz</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/817823923&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/rust" title="rust + maknae" target="_blank" style="color: #cccccc; text-decoration: none;">rust + maknae</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/936327316&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/rundown" title="rundown + @shigitoriii" target="_blank" style="color: #cccccc; text-decoration: none;">rundown + @shigitoriii</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/886533526&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/yandere-srdbeatz-2" title="wasteland + yandere" target="_blank" style="color: #cccccc; text-decoration: none;">wasteland + yandere</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1063968124&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/finally-rich" title="graduation ft @kaiser_wkg, @kurai11, @shigitoriii, @tkyoangel, @waifunerals" target="_blank" style="color: #cccccc; text-decoration: none;">graduation ft @kaiser_wkg, @kurai11, @shigitoriii, @tkyoangel, @waifunerals</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/992466541%3Fsecret_token%3Ds-NOnLOo8HWCG&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/finally-rich-1/s-NOnLOo8HWCG" title="finally rich" target="_blank" style="color: #cccccc; text-decoration: none;">finally rich</a></div>'
  ];
  var featuredBox = document.getElementById('featured-song');
  while(featuredBox.firstChild) {  // Remove all current elements.
    featuredBox.removeChild(featuredBox.firstChild);
  }
  let i = Math.floor(Math.random()) % songs.length;
  const shuffled = songs.sort(() => 0.5 - Math.random());  // Shuffle array
  let selected = shuffled[0];  // Get sub-array of first n elements after shuffled
  var parser = new DOMParser();
  var newNode = parser.parseFromString(selected, "text/html");
  featuredBox.appendChild(newNode.documentElement.childNodes[1].childNodes[0]);
}

shuffle();  // On Page load.