const shuffle = () => {
  var songs = [
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/979782958&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/kaiser_wkg-srdbeatz" title="bailout + @kaiser_wkg" target="_blank" style="color: #cccccc; text-decoration: none;">bailout + @kaiser_wkg</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/934854793&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/derail" title="derail + @1opgloryboyz" target="_blank" style="color: #cccccc; text-decoration: none;">derail + @1opgloryboyz</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/817823923&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/rust" title="rust + maknae" target="_blank" style="color: #cccccc; text-decoration: none;">rust + maknae</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/936327316&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/rundown" title="rundown + @shigitoriii" target="_blank" style="color: #cccccc; text-decoration: none;">rundown + @shigitoriii</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/886533526&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/yandere-srdbeatz-2" title="wasteland + yandere" target="_blank" style="color: #cccccc; text-decoration: none;">wasteland + yandere</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1063968124&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/finally-rich" title="graduation ft @kaiser_wkg, @kurai11, @shigitoriii, @tkyoangel, @waifunerals" target="_blank" style="color: #cccccc; text-decoration: none;">graduation ft @kaiser_wkg, @kurai11, @shigitoriii, @tkyoangel, @waifunerals</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/992466541%3Fsecret_token%3Ds-NOnLOo8HWCG&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/srdbeatz" title="@srdbeatz" target="_blank" style="color: #cccccc; text-decoration: none;">@srdbeatz</a> · <a href="https://soundcloud.com/srdbeatz/finally-rich-1/s-NOnLOo8HWCG" title="finally rich" target="_blank" style="color: #cccccc; text-decoration: none;">finally rich</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1059796258&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/occcti" title="octi" target="_blank" style="color: #cccccc; text-decoration: none;">octi</a> · <a href="https://soundcloud.com/occcti/wartime-srdbeatz-2famous-clubhouse" title="#WarTime @srdbeatz *2FAMOUS CLUBHOUSE*" target="_blank" style="color: #cccccc; text-decoration: none;">#WarTime @srdbeatz *2FAMOUS CLUBHOUSE*</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1055547412&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lilxyu" title="lil yu" target="_blank" style="color: #cccccc; text-decoration: none;">lil yu</a> · <a href="https://soundcloud.com/lilxyu/a-lie-prod-srdbeatz-1" title="a lie (prod. srdbeatz)" target="_blank" style="color: #cccccc; text-decoration: none;">a lie (prod. srdbeatz)</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/981005539&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/captdozzie" title="Capt Dozzie aka Lil Yawh" target="_blank" style="color: #cccccc; text-decoration: none;">Capt Dozzie aka Lil Yawh</a> · <a href="https://soundcloud.com/captdozzie/watuknoabtthat" title="WAT U KNO ABT THAT (prod. SRDBEATZ)" target="_blank" style="color: #cccccc; text-decoration: none;">WAT U KNO ABT THAT (prod. SRDBEATZ)</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/897182194&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ongotaj" title="ONGOTAJ @ONGOTAJ" target="_blank" style="color: #cccccc; text-decoration: none;">ONGOTAJ @ONGOTAJ</a> · <a href="https://soundcloud.com/ongotaj/say-cheese-w-lil-yawh-aka-capt-dozzie-srd" title="Say Cheese! + Lil Yawh [SRD + SHIGITORI]" target="_blank" style="color: #cccccc; text-decoration: none;">Say Cheese! + Lil Yawh [SRD + SHIGITORI]</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/955592749&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/i9bonsai" title="i9bonsai" target="_blank" style="color: #cccccc; text-decoration: none;">i9bonsai</a> · <a href="https://soundcloud.com/i9bonsai/goin2myhed" title="goin2my hed" target="_blank" style="color: #cccccc; text-decoration: none;">goin2my hed</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/965723095&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/pxpidom" title="Dom Corleo" target="_blank" style="color: #cccccc; text-decoration: none;">Dom Corleo</a> · <a href="https://soundcloud.com/pxpidom/monkey-nuts-feat-armani-prod-jxyy2k-srdbeatz" title="Monkey Nuts feat. Armani (Prod. Jxyy2k &amp; Srdbeatz)" target="_blank" style="color: #cccccc; text-decoration: none;">Monkey Nuts feat. Armani (Prod. Jxyy2k &amp; Srdbeatz)</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/754447513&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/kevinsavior" title="kevinhilfiger" target="_blank" style="color: #cccccc; text-decoration: none;">kevinhilfiger</a> · <a href="https://soundcloud.com/kevinsavior/flashbang-p-srdbeatz" title="#flashbang *p SRDBEATZ* OMFG" target="_blank" style="color: #cccccc; text-decoration: none;">#flashbang *p SRDBEATZ* OMFG</a></div>',
    '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/987729916&color=%23ff5500&auto_play=true&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/chiefedsamurai" title="Chiefed Samurai" target="_blank" style="color: #cccccc; text-decoration: none;">Chiefed Samurai</a> · <a href="https://soundcloud.com/chiefedsamurai/zombie-srdbeatz-x-o9seren1ty" title="Zombie (+srdbeatz x o9seren1ty)" target="_blank" style="color: #cccccc; text-decoration: none;">Zombie (+srdbeatz x o9seren1ty)</a></div>'
  ];
  var featuredBox = document.getElementById('featured-song');
  while(featuredBox.firstChild) {  // Remove all current elements.
    featuredBox.removeChild(featuredBox.firstChild);
  }
  let i = Math.floor(Math.random()) % songs.length;
  const shuffled = songs.sort(() => 0.5 - Math.random());  // Shuffle array
  let selected = shuffled[0];  // Get sub-array of first n elements after shuffled
  var parser = new DOMParser();
  var newNode = parser.parseFromString(selected, "text/html");
  featuredBox.appendChild(newNode.documentElement.childNodes[1].childNodes[0]);
}

shuffle();  // On Page load.
